<?php
/*
 * functions.php
 * include autoload generated generated by Composer
 */
require_once TEMPLATEPATH . '/vendor/autoload.php';
require( "class/logger.php");

/*
 * by default log all message in log.txt
 */
$log = new Logger(  );

$log->info('We just got the logger');
$log->warn('Warning!!!');
$log->err('An error occurred');


/*
 * customize name, path and log level
 */
$args = array(
            'name'  => 'Template_Log',
            'path'  => TEMPLATEPATH . '/logs/template.log',
            'level' =>  400, // ERROR
            );

$log2 = new Logger( $args );

$log2->err('This one is template error');


/*
 * load class to log query
 */
require( "class/SmfDayTheme.php");

if ( is_home() ) {
    new SmfDayTheme( );
}

