<?php

/*
 * functions.php
 * include autoload generated generated by Composer
 */
require_once TEMPLATEPATH . '/vendor/autoload.php';

if ( !is_admin()) {

    // include lib
    include("libs/assetic.php");
    include("libs/load-script.php");

    // load js file
    add_action( 'wp_enqueue_scripts', 'load_script' );

    // run merge + minification
    add_action( 'wp_footer', 'run_assetic' , 1);

}
        
        
        
    



